name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: arthascnhub/arthasdevhalo
  VERSION: latest  # 或使用 ${{ github.sha }} 作为唯一版本号

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # GitHub托管Runner
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17 (兼容Alibaba Cloud Linux 3)
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven (示例)
        run: |
          mvn clean package -DskipTests
          ls -lh target/*.jar

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          build-args: |
            BASE_IMAGE=eclipse-temurin:17-jre-jammy  # 与Alibaba Cloud Linux兼容的镜像
